CREATE TABLE Bills (
	Id INT NOT NULL AUTO_INCREMENT,
	DisplayName TEXT NOT NULL,
	PRIMARY KEY (Id)
);

CREATE TABLE RecurranceFrequency (
	Id INT NOT NULL AUTO_INCREMENT,
	DisplayName VARCHAR(32) NOT NULL,
	PRIMARY KEY (Id)
);
ALTER TABLE RecurranceFrequency ADD NumMonths INT NOT NULL;

CREATE TABLE RecurringBills (
	Id INT NOT NULL,
	Enabled BIT NOT NULL DEFAULT TRUE,
	RecurranceFrequencyId INT NOT NULL,
	FOREIGN KEY (Id) REFERENCES Bills(Id)
	ON UPDATE CASCADE
	ON DELETE CASCADE,
	FOREIGN KEY (RecurranceFrequencyId) REFERENCES RecurranceFrequency(Id),
	PRIMARY KEY (Id)
);

CREATE TABLE Payments (
	Id INT NOT NULL,
	BillId INT NOT NULL,
	Amount DECIMAL(13,2) NOT NULL,
	PaymentDate DATETIME NOT NULL,
	Notes TEXT NOT NULL,
	ReceiptLocation TEXT NOT NULL,
	FOREIGN KEY (BillId) REFERENCES Bills(Id),
	PRIMARY KEY (Id)
);
ALTER TABLE Payments MODIFY Id INT NOT NULL AUTO_INCREMENT;